### ISSUE TITLE
Rename index.jsx as index.js

### ISSUE THREAD

**Issue by rangwani-harsh** [allenai/allennlp-simple-server-visualization#2]
When executing the command npm start the following error occurs
```
  Could not find a required file.
  Name: index.js
  Searched in: /home/harsh/NLP tools/irony-detection-allennlp-basic/demo/src
```

This could be easily solved by renaming index.js as index.jsx. 
Reference: https://stackoverflow.com/questions/51016976/renaming-index-js-to-index-jsx-in-react-app

**Comment by matt-gardner** [comment]
Feel free to submit a PR for this!
